@HotelListing_API_HostAddress = https://localhost:7290



GET {{HotelListing_API_HostAddress}}/api/countries

###

@id=2
GET {{HotelListing_API_HostAddress}}/api/countries/{{id}}

###

GET {{HotelListing_API_HostAddress}}/api/hotels

###
@id=1
GET {{HotelListing_API_HostAddress}}/api/hotels/{{id}}

###

POST {{HotelListing_API_HostAddress}}/api/hotels
Content-Type: application/json

{
  "Tilte":"Sheikh Mehmed",
  "Rating":4.9,
  "CountryId":2
}

###

POST {{HotelListing_API_HostAddress}}/api/countries
Content-Type: application/json

{
  "Name": "Iran"
}

###
@id=2
PUT {{HotelListing_API_HostAddress}}/api/countries/{{id}}
Content-Type: application/json

{
  
}

###

PUT {{HotelListing_API_HostAddress}}/api/hotels/{id}
Content-Type: application/json

{
  //Nullable
}

###
