@HotelListing_API_HostAddress = https://localhost:7290




###

GET {{HotelListing_API_HostAddress}}/api/hotels

###

POST {{HotelListing_API_HostAddress}}/api/hotels
Content-Type: application/json

{
"Title":"Emam Reza",
"Rating":4.3,
"CountryId":1
}

###

@id=8
DELETE {{HotelListing_API_HostAddress}}/api/hotels/{{id}}

###

@id=2
GET {{HotelListing_API_HostAddress}}/api/hotels/{{id}}

###

@id=7
PUT {{HotelListing_API_HostAddress}}/api/hotels/{{id}}
Content-Type: application/json

{
  "id":7,
  "Title":"Rezvan",
  "Rating": 2.6,
  "CountryId": 1
}

###
